baseURL: https://akosersek.netlify.app/
languageCode: en-us
title: Portfolio Website for Akos
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      MFA2022 Student at LBS, Warwick Graduate
    title: Hi, my name is Akos. welcome to my Portfolio!
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park, NW1 4SA
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: aersekk@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (44) 677-2109 98
        title: Phone
  custom_css: []
  custom_js: []
  description:
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # icon: fa-twitter
       # label: Twitter
        #url: https://www.twitter.com
      # icon: fa-facebook
       # label: Facebook
        #url: https://www.facebook.com
      # icon: fa-instagram
       # label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/aersekk
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/ersekakos/
  image: ''
  name: Akos Ersek
  navigation:
    button1:
      - name: Projects
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      # name: Blogs
       # url: blogs
      # name: Generic Blog
       # url: blogs/ipsum
      #name: Elements
        #url: elements.html
    menu: Menu
    subtitle: Personal Website
    title: Akos Ersek
  tiles:
    enable: yes
    showcase:
      - image: PictureforR.jpeg
        subtitle: Biography
        title: About me
        url: blogs/blog4
      - image: stock.jpg
        subtitle: A glimpse into the performance of outperforming stocks
        title: Financial Stock
        url: blogs/Blog2
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
